spring:
    application:
        name: ${PRODUCT_SERVICE_APPLICATION_NAME}
    profiles:
        active: default
    data:
        mongodb:
            uri: mongodb://localhost:27017/product-service

    cloud:
        consul:
            config:
                enabled: true
            discovery:
                instance-id: ${spring.application.name}:${random.value}
                prefer-ip-address: true
            host: ${CONSUL_HOST:localhost}
            port: ${CONSUL_PORT:7200}
    security:
        oauth2:
#            client:
#                provider:
#                    my-client:
#                        issuerUri: http://localhost:7800/realms/poc-realm
#                registration:
#                    my-client:
#                        authorizationGrantType: authorization_code
#                        clientId: my-client
#                        clientSecret: TGyd7N71m6iDpkeh78rQ178pqZE8bm6U
#                        redirectUri: http://localhost:9000/login/oauth2/code/my-client
#                        scope:
#                            - openid
#                            - profile
#                            - email
#                            - roles
#                            - offline_access
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7800/realms/poc-realm
                    jwk-set-uri: http://localhost:7800/realms/poc-realm/protocol/openid-connect/certs
                opaquetoken:
                    client-id: my-client
                    client-secret: TGyd7N71m6iDpkeh78rQ178pqZE8bm6U
                    introspection-uri: http://localhost:7800/realms/poc-realm/protocol/openid-connect/token/introspect


tracing:
    url: http://10.0.61.255:4318/v1/traces

management:
    tracing:
        sampling:
            probability: 1.0

logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

---
spring:
    config:
        activate:
            on-profile: default
        import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/local-config

---
spring:
    config:
        activate:
            on-profile: dev
        import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/dev-config
