server:
    port: 9000
spring:
    application:
        name: API-GATEWAY-SERVICE
    cloud:
        consul:
            config:
                enabled: true
            discovery:
                instance-id: ${spring.application.name}:${random.value}
                prefer-ip-address: true
            host: localhost
            port: 7200
        gateway:
            routes:
                - id: INVENTORY-SERVICE
                  uri: lb://INVENTORY-SERVICE
                  predicates:
                      - Path=/api/inventory/**

                - id: ORDER-SERVICE
                  uri: lb://ORDER-SERVICE
                  predicates:
                        - Path=/api/order/**

                - id: PRODUCT-SERVICE-DEV
                  uri: lb://PRODUCT-SERVICE
                  predicates:
                        - Path=/api/product/**
    config:
        import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/dev-config
#    main:
#        allow-bean-definition-overriding: true
    security:
        oauth2:
            client:
                provider:
                    my-client:
                        issuerUri: http://localhost:7800/realms/poc-realm
                registration:
                    my-client:
                        authorizationGrantType: authorization_code
                        clientId: my-client
                        clientSecret: TGyd7N71m6iDpkeh78rQ178pqZE8bm6U
                        redirectUri: http://localhost:9000/login/oauth2/code/my-client
                        scope:
                            - openid
                            - profile
                            - email
                            - roles
                            - offline_access
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7800/realms/poc-realm
                    jwk-set-uri: http://localhost:7800/realms/poc-realm/protocol/openid-connect/certs
                opaquetoken:
                    client-id: my-client
                    client-secret: TGyd7N71m6iDpkeh78rQ178pqZE8bm6U
                    introspection-uri: http://localhost:7800/realms/poc-realm/protocol/openid-connect/token/introspect

tracing:
    url: http://10.0.61.255:4318/v1/traces

management:
    tracing:
        sampling:
            probability: 1.0

logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'




